### PR TITLE
Compile grammar via command

### PR DESCRIPTION
**Pull request by burodepeper**
Sorry for the previous erroneous PR.

When in Atom in dev-mode, press <kbd>cmd+shift+p</kbd> and search for `compile`. The command `Shellscript: Compile Grammar and Reload` should pop up. Execute it, and the compiled grammar will be written to `/grammars/unix-shell.json`.

You can see in the diff that I've removed `grammars/unix-shell.cson`, because that would have caused a conflict with the compiled JSON with the same name.

The compiled grammar isn't complete yet, but this should at least help you on the way.

### CODE REVIEW

**Comment by fusion809** [comment]
Can I use the same key in two different repository files? Like I want to have a punctuation/definition.cson and variables/definition.cson file both using the `key` value of 'definition'.

**Comment by burodepeper** [comment]
Nope, that won't work if they become part of the same compiled repository. A `key` in a grammar should be unique. How would your grammar know otherwise which version of `#definition` it should use?

**Comment by fusion809** [comment]
OK. Thanks.

**Comment by fusion809** [comment]
I just attempted to fill out shell.cson and unix-shell.json files, and I'm afraid it isn't working. Before you ask if I remembered to compile the grammars I opened the command pallette as you suggested and no options came up when I typed "Compile" besides the incompatible packages rebuild option. 

It gave this error report:

> [Enter steps to reproduce below:]
> 1. ...
> 2. ...
> 
> **Atom Version**: 1.8.0
> **System**: "Arch Linux"
> **Thrown From**: [language-unix-shell](https://github.com/fusion809/language-shellscript) package, v0.31.3
> 
> ### Stack Trace
> 
> Failed to load a language-unix-shell package grammar
> 
> ```
> At /home/fusion809/.atom/packages/language-unix-shell/grammars/unix-shell.json: Unexpected string in /home/fusion809/.atom/packages/language-unix-shell/grammars/unix-shell.json
> 
> SyntaxError: /home/fusion809/.atom/packages/language-unix-shell/grammars/unix-shell.json: Unexpected string
>     at Object.parse (native)
>     at parseObject (/usr/share/atom/resources/app.asar/node_modules/season/lib/cson.js:54:19)
>     at parseContents (/usr/share/atom/resources/app.asar/node_modules/season/lib/cson.js:102:16)
>     at /usr/share/atom/resources/app.asar/node_modules/season/lib/cson.js:204:20
>     at tryToString (fs.js:414:3)
>     at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:401:12)
>   at /home/fusion809/.atom/packages/language-unix-shell/grammars/unix-shell.json:1:1
> ```
> 
> ### Commands
> 
> ```
> ```
> 
> ### Config
> 
> ``` json
> {
>   "core": {
>     "disabledPackages": [
>       "about",
>       "language-gfm",
>       "language-shellscript"
>     ],
>     "projectHome": "/home/fusion809/GitHub/mine",
>     "themes": [
>       "fusion-ui",
>       "dark-bint-syntax"
>     ]
>   }
> }
> ```
> 
> ### Installed Packages
> 
> ``` coffee
> # User
> autocomplete-modules, v1.5.1
> autocomplete-python, v1.8.1
> autocomplete-sass, v0.1.0
> browser-plus-fix, v0.1.3
> dark-bint-syntax, v0.8.8
> file-icons, v1.7.14
> fusion-ui, v0.10.8
> language-asciidoc, v1.5.1
> language-debian, v0.2.1
> language-docker, v1.1.6
> language-rpm-spec, v0.10.0
> language-rust, v0.4.6
> language-solus, v0.1.0
> language-unix-shell, v0.31.3
> linter-coffeescript, v1.0.0
> minimap, v4.24.6
> package-sync, v1.1.0
> pigments, v0.29.2
> terminal-fusion, v2.1.4
> 
> # Dev
> No dev packages
> ```

**Comment by burodepeper** [comment]
> No dev packages

I think that you haven't linked the package to dev mode. Open a terminal and go to the directory of the package and type `apm link -d`. Now reload Atom and try again. If you get some sort of "not found" error (I got a `season` not found error), try `npm install` from the package directory via terminal, and reload Atom, and try again.

Note: there's no need to manually change anything in the output JSON. It will be overwritten anytime you compile the grammar.

**Comment by fusion809** [comment]
Ah now it's compiling and here's the json https://gist.github.com/fusion809/cf1293a40c78b059d832a9c33ea33b9e. 

**EDIT**: But it's not syntax-highlighting at all.

**Comment by fusion809** [comment]
Ah in case ya missed my edit there's no syntax-highlighting of shell scripts, at all. Here's a screenshot I launched this window with `atom --dev $SHL` (where `$SHL` is defined in my `~/.zshrc` file as `$HOME/Shell`) **after** compiling the grammars. 

screenshot_20160616_000746

**Comment by burodepeper** [comment]
I've pulled your changes, and the compiled `.json` doesn't contain the repos anymore. Throws the following (probably related) error:

```
SyntaxError: /Users/david/.atom/dev/packages/language-unix-shell/grammars/unix-shell.json: Unexpected string
    at Object.parse (native)
    at parseObject (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/season/lib/cson.js:54:19)
    at parseContents (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/season/lib/cson.js:102:16)
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/season/lib/cson.js:204:20
    at tryToString (fs.js:414:3)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:401:12)
  at /Users/david/.atom/dev/packages/language-unix-shell/grammars/unix-shell.json:1:1
```

Don't forget to commit and sync the compiled JSON. When I compile the grammar (note: this is something that you have to do manually before publishing, it's not something that happens after a user install the package) the package loads just fine.

After compiling the grammar, I get the following error in the Chrome console in Atom: `Popping rule because it loops at column 0 of line ''` (in the first-mate package). I think that there's an error in your grammar code somewhere, but I'll leave the checking almost 2000 lines of grammar to you.

In the console, I can see that everything in a test shell document is scoped as `meta.scope.case-pattern.shell`, so it at least does something. Maybe that helps you a bit further.

**Pull request merged**
